config/routes.rb
Rails.application.routes.draw do
  root to: 'players#index'
  resources :players, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  require 'csv'
  self.per_page = 25

  def self.to_csv(players)
    CSV.generate do |csv|
      data_columns = column_names.filter{ |col| !["id", "created_at", "updated_at"].include?(col) }
      csv << data_columns
      players.each do |player|
        csv << player.attributes.values_at(*data_columns)
      end
    end
  end

  def self.load_json(records)
    records.each do |rec|
      Player.create!({ name: rec['Player'], team: rec['Team'], position: rec['Pos'],
                       attempts_per_game: safe_load_float(rec['Att']),
                       total_attempts: safe_load_int(rec['Att/G']), total_yards: safe_load_int(rec['Yds']),
                       average_yards_per_attempt: safe_load_float(rec['Avg']),
                       yards_per_game: safe_load_float(rec['Yds/G']),
                       rushing_touchdowns: safe_load_int(rec['TD']),
                       longest_rush: safe_load_longest_rush(rec['Lng']),
                       longest_rush_is_touchdown: is_rush_td?(rec['Lng']),
                       first_downs: safe_load_int(rec['1st']),
                       first_downs_percent: safe_load_float(rec['1st%']),
                       twenty_plus: safe_load_int(rec['20+']), forty_plus: safe_load_int(rec['40+']),
                       fumbles: safe_load_int(rec['FUM']) })
    end
  end

  def self.safe_load_int(input)
    input.to_s.delete(',').to_i
  end

  def self.safe_load_float(input)
    input.to_s.delete(',').to_f
  end

  def self.safe_load_longest_rush(input)
    safe_load_int(input.to_s.delete('t', 'T'))
  end

  def self.is_rush_td?(input)
    input.to_s.upcase.ends_with?('T')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.csv
  def index
    @search = Player.ransack(params[:q])
    respond_to do |format|
      format.html { @players = @search.result.page(params[:page]) }
      format.csv {  send_data Player.to_csv(@search.result), filename: "rushing.csv" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NflRushing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_players.html.erb
<%= search_form_for @search do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name_cont, class: 'form-control' %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<table class="table table-striped table-bordered table-condensed table-hover">
  <thead class="thead-dark">


  <tr>
    <th><%= link_to players_path(request.parameters.merge({format: 'csv'})), class: 'btn btn-primary' do %> Export <% end %></th>
    <th>Name</th>
    <th>Team</th>
    <th>Position</th>
    <th>Attempts/game</th>
    <th>Total attempts</th>
    <th><%= sort_link(@search, :total_yards) %></th>
    <th>Average Yards/Attempt</th>
    <th>Yards/Game</th>
    <th><%= sort_link(@search, :rushing_touchdowns) %></th>
    <th><%= sort_link(@search, :longest_rush) %></th>
    <th>Longest Rush is touchdown</th>
    <th>First Downs</th>
    <th>First Downs %</th>
    <th>20+ Yards</th>
    <th>40+ Yards</th>
    <th>Fumbles</th>
  </tr>
  </thead>

  <tbody>
  <% @players.each do |player| %>
    <tr>
      <td></td>
      <td><%= player.name %></td>
      <td><%= player.team %></td>
      <td><%= player.position %></td>
      <td><%= player.attempts_per_game %></td>
      <td><%= player.total_attempts %></td>
      <td><%= player.total_yards %></td>
      <td><%= player.average_yards_per_attempt %></td>
      <td><%= player.yards_per_game %></td>
      <td><%= player.rushing_touchdowns %></td>
      <td><%= player.longest_rush %></td>
      <td><%= player.longest_rush_is_touchdown %></td>
      <td><%= player.first_downs %></td>
      <td><%= player.first_downs_percent %></td>
      <td><%= player.twenty_plus %></td>
      <td><%= player.forty_plus %></td>
      <td><%= player.fumbles %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @players, list_classes: %w(pagination justify-content-end) %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players: Rushing</h1>

<div id="players"><%= render 'players' %></div>